export const EV = {
  primary: '#00E676',
  primaryDark: '#00C853',
  primaryDeep: '#00BFA5',
  accent: '#69F0AE',
  accentSoft: '#B9F6CA',
  neon: '#76FF03',
  bg: '#050F0A',
  bgCard: '#0A1F14',
  bgSurface: '#0D2B1A',
  bgElevated: '#112E1C',
  border: '#1A4A2A',
  borderGlow: '#00E67640',
  text: '#E8FFF2',
  textMuted: '#6DBF8A',
  textDim: '#3A7A52',
  danger: '#FF5252',
  warning: '#FFD740',
  info: '#40C4FF',
  white: '#FFFFFF',
};

export const Colors = {
  light: {
    text: EV.text,
    background: EV.bg,
    tint: EV.primary,
    icon: EV.textMuted,
    tabIconDefault: EV.textDim,
    tabIconSelected: EV.primary,
  },
  dark: {
    text: EV.text,
    background: EV.bg,
    tint: EV.primary,
    icon: EV.textMuted,
    tabIconDefault: EV.textDim,
    tabIconSelected: EV.primary,
  },
};
